#parameters
batch_size = 128
input_size  = 112
embd_shape = 512
sub_name = 'arc_mobv2' #arc_rec50 or arc_mobv2
backbone_type = 'MobileNetV2' # 'ResNet50', 'MobileNetV2'
head_type = "ArcHead" # 'ArcHead', 'NormHead'
is_ccrop = False # central-cropping or not
binary_img = True
num_classes = 85742
num_samples = 5473293
epochs = 5
base_lr = 0.01
w_decay = float(5e-4)
save_steps = 500
